# Generated by Django 5.0.4 on 2024-07-28 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_management', '0002_linesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linefriend',
            name='user',
        ),
    ]
