# Generated by Django 5.0.4 on 2024-06-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(default='default_company_name', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kana',
            field=models.CharField(default='default_kana', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='default_name', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='000-0000-0000', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(default='000-0000', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscription_plan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
