# Generated by Django 5.0.4 on 2024-07-25 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_management', '0002_linesettings'),
        ('score_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('memo', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('line_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_management.linefriend')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score_management.statussetting')),
            ],
        ),
    ]
