# Generated by Django 5.0.4 on 2024-07-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_management', '0002_userscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
