# Generated by Django 5.0.4 on 2024-08-09 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_management', '0004_tag_linefriendtag'),
        ('score_management', '0004_alter_userscore_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='memo',
        ),
        migrations.AddField(
            model_name='scoresetting',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='line_management.tag'),
        ),
    ]
