# Generated by Django 5.0.4 on 2024-12-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_management', '0006_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresetting',
            name='trigger',
            field=models.CharField(max_length=500),
        ),
    ]
